# !/bin/bash
# enable flatpaks
sudo zypper --non-interactive install flatpak
flatpak remote-add --if-not-exists flathub https://dl.flathub.org/repo/flathub.flatpakrepo

# enable snaps
sudo zypper addrepo --refresh \https://download.opensuse.org/repositories/system:/snappy/openSUSE_Tumbleweed \snappy
sudo zypper --gpg-auto-import-keys refresh
sudo zypper dup --from snappy
sudo zypper --non-interactive install snapd
source ~/.bashrc
sudo systemctl enable --now snapd
sudo snap install snap-store

###### Packages ########

sudo zypper --non-interactive in a2jmidid
sudo zypper --non-interactive in alsa-oss-32bit
sudo zypper --non-interactive in ardour
sudo zypper --non-interactive in attica-qt5
sudo zypper --non-interactive in audaspace-plugin-ffmpeg
sudo zypper --non-interactive in audaspace-plugin-jack
sudo zypper --non-interactive in autoconf
sudo zypper --non-interactive in automake
sudo zypper --non-interactive in bamf-daemon
sudo zypper --non-interactive in baobab
sudo zypper --non-interactive in baobab-lang
sudo zypper --non-interactive in bin86
sudo zypper --non-interactive in binutils
sudo zypper --non-interactive in binutils-devel
sudo zypper --non-interactive in binutils-devel-32bit
sudo zypper --non-interactive in bison
sudo zypper --non-interactive in bison-32bit
sudo zypper --non-interactive in bison-lang
sudo zypper --non-interactive in blender
sudo zypper --non-interactive in blender-demo
sudo zypper --non-interactive in blender-lang
sudo zypper --non-interactive in bluez-qt-imports
sudo zypper --non-interactive in bluez-zsh-completion
sudo zypper --non-interactive in breeze5-icons
sudo zypper --non-interactive in bsdiff
sudo zypper --non-interactive in bubblewrap-zsh-completion
sudo zypper --non-interactive in ca-certificates-steamtricks
sudo zypper --non-interactive in calf
sudo zypper --non-interactive in calligra-extras-filemanagertemplates
sudo zypper --non-interactive in carla
sudo zypper --non-interactive in carla-devel
sudo zypper --non-interactive in carla-vst
sudo zypper --non-interactive in cepces
sudo zypper --non-interactive in cepces-certmonger
sudo zypper --non-interactive in certmonger
sudo zypper --non-interactive in chafa
sudo zypper --non-interactive in cyrus-sasl-devel
sudo zypper --non-interactive in darktable
sudo zypper --non-interactive in darktable-tools-basecurve
sudo zypper --non-interactive in darktable-tools-noise
sudo zypper --non-interactive in dcraw
sudo zypper --non-interactive in dcraw-lang
sudo zypper --non-interactive in docbook_4
sudo zypper --non-interactive in docbook-xsl-stylesheets
sudo zypper --non-interactive in dosbox
sudo zypper --non-interactive in drkonqi5
sudo zypper --non-interactive in dssi
sudo zypper --non-interactive in dvdauthor
sudo zypper --non-interactive in dvgrab
sudo zypper --non-interactive in dwarves
sudo zypper --non-interactive in dxvk
sudo zypper --non-interactive in dxvk-32bit
sudo zypper --non-interactive in e2fsprogs-devel
sudo zypper --non-interactive in easyeffects-doc
sudo zypper --non-interactive in exiftool
sudo zypper --non-interactive in fastfetch
sudo zypper --non-interactive in fetchmsttfonts
sudo zypper --non-interactive in ffmpeg-6
sudo zypper --non-interactive in filezilla
sudo zypper --non-interactive in filezilla-lang
sudo zypper --non-interactive in firewalld-zsh-completion
sudo zypper --non-interactive in flatpak-spawn
sudo zypper --non-interactive in flatpak-xdg-utils
sudo zypper --non-interactive in flatpak-zsh-completion
sudo zypper --non-interactive in flex
sudo zypper --non-interactive in fluid-soundfont-gm
sudo zypper --non-interactive in fluid-soundfont-gs
sudo zypper --non-interactive in fontconfig-32bit
sudo zypper --non-interactive in frei0r-plugins
sudo zypper --non-interactive in fuseiso
sudo zypper --non-interactive in gamemode
sudo zypper --non-interactive in gamemoded
sudo zypper --non-interactive in gcc
sudo zypper --non-interactive in gcc13
sudo zypper --non-interactive in gcc13-32bit
sudo zypper --non-interactive in gcc13-c++
sudo zypper --non-interactive in gcc13-c++-32bit
sudo zypper --non-interactive in gcc13-info
sudo zypper --non-interactive in gcc-32bit
sudo zypper --non-interactive in gcc-c++
sudo zypper --non-interactive in gcc-c++-32bit
sudo zypper --non-interactive in gcc-info
sudo zypper --non-interactive in gdbm-devel
sudo zypper --non-interactive in gdbm-devel-32bit
sudo zypper --non-interactive in gdk-pixbuf-query-loaders-32bit
sudo zypper --non-interactive in gettext-tools
sudo zypper --non-interactive in git
sudo zypper --non-interactive in git-core
sudo zypper --non-interactive in git-email
sudo zypper --non-interactive in git-gui
sudo zypper --non-interactive in gitk
sudo zypper --non-interactive in git-svn
sudo zypper --non-interactive in glibc-32bit
sudo zypper --non-interactive in glibc-devel
sudo zypper --non-interactive in glibc-devel-32bit
sudo zypper --non-interactive in glibc-info
sudo zypper --non-interactive in glibc-locale-base-32bit
sudo zypper --non-interactive in gmp-devel
sudo zypper --non-interactive in gmp-devel-32bit
sudo zypper --non-interactive in gnome-keyring-32bit
sudo zypper --non-interactive in gnome-keyring-pam-32bit
sudo zypper --non-interactive in gnuplot
sudo zypper --non-interactive in goverlay
sudo zypper --non-interactive in gparted
sudo zypper --non-interactive in gparted-lang
sudo zypper --non-interactive in gperf
sudo zypper --non-interactive in graphviz
sudo zypper --non-interactive in graphviz-gd
sudo zypper --non-interactive in graphviz-gnome
sudo zypper --non-interactive in graphviz-plugins-core
sudo zypper --non-interactive in gstreamer-32bit
sudo zypper --non-interactive in gtk2-engine-clearlooks
sudo zypper --non-interactive in gtk2-engine-oxygen-32bit
sudo zypper --non-interactive in gtk2-theme-clearlooks
sudo zypper --non-interactive in gtk2-theming-engine-adwaita-32bit
sudo zypper --non-interactive in gtk2-tools-32bit
sudo zypper --non-interactive in gvfs-backend-afc
sudo zypper --non-interactive in hexchat
sudo zypper --non-interactive in hexchat-lang
sudo zypper --non-interactive in hfsutils
sudo zypper --non-interactive in highlight
sudo zypper --non-interactive in highlight-bash-completion
sudo zypper --non-interactive in highlight-common
sudo zypper --non-interactive in highlight-zsh-completion
sudo zypper --non-interactive in hydrogen
sudo zypper --non-interactive in icoutils
sudo zypper --non-interactive in inkscape
sudo zypper --non-interactive in inkscape-extensions-extra
sudo zypper --non-interactive in inkscape-extensions-gimp
sudo zypper --non-interactive in inkscape-lang
sudo zypper --non-interactive in iso_ent
sudo zypper --non-interactive in J7Z
sudo zypper --non-interactive in jacktrip
sudo zypper --non-interactive in jfsutils
sudo zypper --non-interactive in jq
sudo zypper --non-interactive in kaccounts-integration
sudo zypper --non-interactive in kaccounts-providers
sudo zypper --non-interactive in kate
sudo zypper --non-interactive in kate-lang
sudo zypper --non-interactive in kate-plugins
sudo zypper --non-interactive in kconf_update5
sudo zypper --non-interactive in kcoreaddons
sudo zypper --non-interactive in kcoreaddons-lang
sudo zypper --non-interactive in kdbusaddons-tools
sudo zypper --non-interactive in kdeclarative-components
sudo zypper --non-interactive in kded
sudo zypper --non-interactive in kdenlive
sudo zypper --non-interactive in kdenlive-lang
sudo zypper --non-interactive in kdoctools
sudo zypper --non-interactive in keepassxc
sudo zypper --non-interactive in keepassxc-lang
sudo zypper --non-interactive in kernel-default-devel
sudo zypper --non-interactive in kernel-devel
sudo zypper --non-interactive in kernel-macros
sudo zypper --non-interactive in kfilemetadata5
sudo zypper --non-interactive in kglobalaccel5
sudo zypper --non-interactive in kguiaddons
sudo zypper --non-interactive in kinit
sudo zypper --non-interactive in kio
sudo zypper --non-interactive in kio-core
sudo zypper --non-interactive in kirigami2
sudo zypper --non-interactive in kitemmodels-imports
sudo zypper --non-interactive in knewstuff
sudo zypper --non-interactive in kompare
sudo zypper --non-interactive in kpackage
sudo zypper --non-interactive in krb5-32bit
sudo zypper --non-interactive in kservice
sudo zypper --non-interactive in ktexteditor
sudo zypper --non-interactive in kuserfeedback-imports
sudo zypper --non-interactive in kuserfeedback-lang
sudo zypper --non-interactive in lib2geom1_2_0
sudo zypper --non-interactive in liba52-0
sudo zypper --non-interactive in libaccounts-glib0
sudo zypper --non-interactive in libaccounts-qt5-1
sudo zypper --non-interactive in libacl1-32bit
sudo zypper --non-interactive in libaio1-32bit
sudo zypper --non-interactive in libaio-devel
sudo zypper --non-interactive in libaio-devel-32bit
sudo zypper --non-interactive in libAlembic1_8
sudo zypper --non-interactive in libaom3-32bit
sudo zypper --non-interactive in libapparmor-devel
sudo zypper --non-interactive in libapr1-0
sudo zypper --non-interactive in libapr-util1-0
sudo zypper --non-interactive in libasan8
sudo zypper --non-interactive in libasan8-32bit
sudo zypper --non-interactive in libasound2-32bit
sudo zypper --non-interactive in libatk-1_0-0-32bit
sudo zypper --non-interactive in libatomic1-32bit
sudo zypper --non-interactive in libaubio5
sudo zypper --non-interactive in libaudaspace1_4
sudo zypper --non-interactive in libaudaspace-c1_4
sudo zypper --non-interactive in libaudaspace-py1_4
sudo zypper --non-interactive in libaudit1-32bit
sudo zypper --non-interactive in libavahi-client3-32bit
sudo zypper --non-interactive in libavahi-common3-32bit
sudo zypper --non-interactive in libavc1394-0
sudo zypper --non-interactive in libavcodec58_134
sudo zypper --non-interactive in libavcodec59
sudo zypper --non-interactive in libavdevice58_13
sudo zypper --non-interactive in libavdevice59
sudo zypper --non-interactive in libavdevice60
sudo zypper --non-interactive in libavfilter7_110
sudo zypper --non-interactive in libavfilter8
sudo zypper --non-interactive in libavformat58_76
sudo zypper --non-interactive in libavformat59
sudo zypper --non-interactive in libavif15-32bit
sudo zypper --non-interactive in libavresample4_0
sudo zypper --non-interactive in libavutil56_70
sudo zypper --non-interactive in libavutil57
sudo zypper --non-interactive in libb2-1
sudo zypper --non-interactive in libbamf3-2
sudo zypper --non-interactive in libblkid1-32bit
sudo zypper --non-interactive in libblkid-devel
sudo zypper --non-interactive in libblosc1
sudo zypper --non-interactive in libbluetooth3-32bit
sudo zypper --non-interactive in libboost_atomic1_82_0
sudo zypper --non-interactive in libboost_chrono1_82_0
sudo zypper --non-interactive in libboost_date_time1_82_0
sudo zypper --non-interactive in libboost_regex1_82_0
sudo zypper --non-interactive in libboost_system1_82_0
sudo zypper --non-interactive in libboost_wave1_82_0
sudo zypper --non-interactive in libbotan-2-19
sudo zypper --non-interactive in libbrotlicommon1-32bit
sudo zypper --non-interactive in libbrotlidec1-32bit
sudo zypper --non-interactive in libbuffer0_3
sudo zypper --non-interactive in libbz2-1-32bit
sudo zypper --non-interactive in libcaca0
sudo zypper --non-interactive in libcairo2-32bit
sudo zypper --non-interactive in libcamera0_0_4-32bit
sudo zypper --non-interactive in libcamera-base0_0_4-32bit
sudo zypper --non-interactive in libcanberra0-32bit
sudo zypper --non-interactive in libcanberra-gtk0-32bit
sudo zypper --non-interactive in libcanberra-gtk2-module-32bit
sudo zypper --non-interactive in libcap2-32bit
sudo zypper --non-interactive in libcapi20-3
sudo zypper --non-interactive in libcapi20-3-32bit
sudo zypper --non-interactive in libcblas3
sudo zypper --non-interactive in libcelt0-2
sudo zypper --non-interactive in libcerf2
sudo zypper --non-interactive in libchafa0
sudo zypper --non-interactive in libclang-cpp15
sudo zypper --non-interactive in libcolord-gtk1
sudo zypper --non-interactive in libcom_err2-32bit
sudo zypper --non-interactive in libcom_err-devel
sudo zypper --non-interactive in libcrack2-32bit
sudo zypper --non-interactive in libcrypt1-32bit
sudo zypper --non-interactive in libctf0
sudo zypper --non-interactive in libctf-nobfd0
sudo zypper --non-interactive in libcups2-32bit
sudo zypper --non-interactive in libcurl4-32bit
sudo zypper --non-interactive in libdatrie1-32bit
sudo zypper --non-interactive in libdav1d6-32bit
sudo zypper --non-interactive in libdb-4_8-devel
sudo zypper --non-interactive in libdbus-1-3-32bit
sudo zypper --non-interactive in libdbus-glib-1-2-32bit
sudo zypper --non-interactive in libdbusmenu-qt5-2
sudo zypper --non-interactive in libdcmtk17
sudo zypper --non-interactive in libdiscord-rpc3_4_0
sudo zypper --non-interactive in libdmtx0
sudo zypper --non-interactive in libdotconf0
sudo zypper --non-interactive in libdrm2-32bit
sudo zypper --non-interactive in libdrm_amdgpu1-32bit
sudo zypper --non-interactive in libdrm_intel1-32bit
sudo zypper --non-interactive in libdrm_nouveau2-32bit
sudo zypper --non-interactive in libdrm_radeon1-32bit
sudo zypper --non-interactive in libdw1-32bit
sudo zypper --non-interactive in libdwarves1
sudo zypper --non-interactive in libebur128-1
sudo zypper --non-interactive in libeconf0-32bit
sudo zypper --non-interactive in libedit0-32bit
sudo zypper --non-interactive in libeditorconfig0
sudo zypper --non-interactive in libefivar1
sudo zypper --non-interactive in libelf1-32bit
sudo zypper --non-interactive in libelf-devel
sudo zypper --non-interactive in libembree3
sudo zypper --non-interactive in libepub0
sudo zypper --non-interactive in libev4
sudo zypper --non-interactive in libexif12-32bit
sudo zypper --non-interactive in libexpat1-32bit
sudo zypper --non-interactive in libext2fs-devel
sudo zypper --non-interactive in libfaad2
sudo zypper --non-interactive in libfdk-aac2-32bit
sudo zypper --non-interactive in libffi8-32bit
sudo zypper --non-interactive in libfftw3_threads3
sudo zypper --non-interactive in libfilezilla35
sudo zypper --non-interactive in libfl2
sudo zypper --non-interactive in libFLAC12-32bit
sudo zypper --non-interactive in libfl-devel
sudo zypper --non-interactive in libfluidsynth3
sudo zypper --non-interactive in libfmt9
sudo zypper --non-interactive in libfontconfig1-32bit
sudo zypper --non-interactive in libfreebl3-32bit
sudo zypper --non-interactive in libfreetype6-32bit
sudo zypper --non-interactive in libfribidi0-32bit
sudo zypper --non-interactive in libftoa0_3
sudo zypper --non-interactive in libgamemode0
sudo zypper --non-interactive in libgamemodeauto0
sudo zypper --non-interactive in libgavl1
sudo zypper --non-interactive in libgbm1-32bit
sudo zypper --non-interactive in libgc1
sudo zypper --non-interactive in libgcc_s1-32bit
sudo zypper --non-interactive in libgcrypt20-32bit
sudo zypper --non-interactive in libgd3-32bit
sudo zypper --non-interactive in libgdbm6-32bit
sudo zypper --non-interactive in libgdbm_compat4-32bit
sudo zypper --non-interactive in libgdk_pixbuf-2_0-0-32bit
sudo zypper --non-interactive in libGeneratedSaxParser0_3
sudo zypper --non-interactive in libgig10
sudo zypper --non-interactive in libgio-2_0-0-32bit
sudo zypper --non-interactive in libGLEW2_2
sudo zypper --non-interactive in libglfw3
sudo zypper --non-interactive in libglib-2_0-0-32bit
sudo zypper --non-interactive in libGLU1
sudo zypper --non-interactive in libglut3
sudo zypper --non-interactive in libglvnd-32bit
sudo zypper --non-interactive in libgmic3
sudo zypper --non-interactive in libgmodule-2_0-0-32bit
sudo zypper --non-interactive in libgmp10-32bit
sudo zypper --non-interactive in libgmpxx4-32bit
sudo zypper --non-interactive in libgobject-2_0-0-32bit
sudo zypper --non-interactive in libgpg-error0-32bit
sudo zypper --non-interactive in libgphoto2_port12-32bit
sudo zypper --non-interactive in libGraphicsMagick++-Q16-12
sudo zypper --non-interactive in libgraphite2-3-32bit
sudo zypper --non-interactive in libgslcblas0
sudo zypper --non-interactive in libgstreamer-1_0-0-32bit
sudo zypper --non-interactive in libgstvideo-1_0-0-32bit
sudo zypper --non-interactive in libgts-0_7-5
sudo zypper --non-interactive in libgvpr2
sudo zypper --non-interactive in libharfbuzz0-32bit
sudo zypper --non-interactive in libhogweed6-32bit
sudo zypper --non-interactive in libhpdf2_4_2
sudo zypper --non-interactive in libhwasan0
sudo zypper --non-interactive in libhydrogen-core-1_2_0
sudo zypper --non-interactive in libICE6-32bit
sudo zypper --non-interactive in libidn2-0-32bit
sudo zypper --non-interactive in libiec61883-0
sudo zypper --non-interactive in libieee12843
sudo zypper --non-interactive in libiir1
sudo zypper --non-interactive in libimagequant0
sudo zypper --non-interactive in libimobiledevice-1_0-6
sudo zypper --non-interactive in libimobiledevice-glue-1_0-0
sudo zypper --non-interactive in libinstpatch-1_0-2
sudo zypper --non-interactive in libitm1
sudo zypper --non-interactive in libitm1-32bit
sudo zypper --non-interactive in libjack0-32bit
sudo zypper --non-interactive in libjansson4-32bit
sudo zypper --non-interactive in libjasper7
sudo zypper --non-interactive in libjavascriptcoregtk-4_0-18
sudo zypper --non-interactive in libjbig2-32bit
sudo zypper --non-interactive in libjitterentropy3-32bit
sudo zypper --non-interactive in libjpeg8-32bit
sudo zypper --non-interactive in libjq1
sudo zypper --non-interactive in libjsoncpp25
sudo zypper --non-interactive in libkaccounts2
sudo zypper --non-interactive in libkate-tools
sudo zypper --non-interactive in libkeyutils1-32bit
sudo zypper --non-interactive in libKF5Activities5
sudo zypper --non-interactive in libKF5Archive5
sudo zypper --non-interactive in libKF5Attica5
sudo zypper --non-interactive in libKF5Auth5
sudo zypper --non-interactive in libKF5Auth5-lang
sudo zypper --non-interactive in libKF5AuthCore5
sudo zypper --non-interactive in libKF5BluezQt6
sudo zypper --non-interactive in libKF5Bookmarks5
sudo zypper --non-interactive in libKF5Codecs5
sudo zypper --non-interactive in libKF5Completion5
sudo zypper --non-interactive in libKF5ConfigCore5
sudo zypper --non-interactive in libKF5ConfigGui5
sudo zypper --non-interactive in libKF5ConfigWidgets5
sudo zypper --non-interactive in libKF5CoreAddons5
sudo zypper --non-interactive in libKF5Crash5
sudo zypper --non-interactive in libKF5DBusAddons5
sudo zypper --non-interactive in libKF5Declarative5
sudo zypper --non-interactive in libKF5DocTools5
sudo zypper --non-interactive in libKF5GlobalAccel5
sudo zypper --non-interactive in libKF5GlobalAccelPrivate5
sudo zypper --non-interactive in libKF5GuiAddons5
sudo zypper --non-interactive in libKF5I18n5
sudo zypper --non-interactive in libKF5IconThemes5
sudo zypper --non-interactive in libKF5IdleTime5
sudo zypper --non-interactive in libKF5ItemModels5
sudo zypper --non-interactive in libKF5ItemViews5
sudo zypper --non-interactive in libKF5Wallet5
sudo zypper --non-interactive in libKF5XmlGui5
sudo zypper --non-interactive in libkomparediff2-lang
sudo zypper --non-interactive in libKUserFeedbackWidgets1
sudo zypper --non-interactive in libldac2-32bit
sudo zypper --non-interactive in libldb2-32bit
sudo zypper --non-interactive in libLLVM15
sudo zypper --non-interactive in liblo7
sudo zypper --non-interactive in liblsan0
sudo zypper --non-interactive in liblz4-1-32bit
sudo zypper --non-interactive in libmad0
sudo zypper --non-interactive in libMathMLSolver0_3
sudo zypper --non-interactive in libmbedcrypto14
sudo zypper --non-interactive in libmbedx509-5
sudo zypper --non-interactive in libmlt++-7-7
sudo zypper --non-interactive in libmlt7-data
sudo zypper --non-interactive in libmms0
sudo zypper --non-interactive in libmpeg2-0
sudo zypper --non-interactive in libmysofa1-32bit
sudo zypper --non-interactive in libnettle8-32bit
sudo zypper --non-interactive in libnilfs0
sudo zypper --non-interactive in libnilfsgc0
sudo zypper --non-interactive in libnm0-32bit
sudo zypper --non-interactive in libnvidia-egl-wayland1
sudo zypper --non-interactive in libonig5
sudo zypper --non-interactive in libopenblas_pthreads0
sudo zypper --non-interactive in libOpenCOLLADAFramework0_3
sudo zypper --non-interactive in libOpenCOLLADAStreamWriter0_3
sudo zypper --non-interactive in libopencore-amrnb0
sudo zypper --non-interactive in libopencv407
sudo zypper --non-interactive in libopencv_videoio407
sudo zypper --non-interactive in libOpenImageDenoise1
sudo zypper --non-interactive in libOpenImageIO_Util2_4
sudo zypper --non-interactive in libopenshot24
sudo zypper --non-interactive in libopenssl1_0_0
sudo zypper --non-interactive in libopenssl1_0_0-steam-32bit
sudo zypper --non-interactive in libopus0-32bit
sudo zypper --non-interactive in liborc-0_4-0-32bit
sudo zypper --non-interactive in libosip2-15
sudo zypper --non-interactive in liboslcomp1_12
sudo zypper --non-interactive in liboslexec1_12
sudo zypper --non-interactive in liboslquery1_12
sudo zypper --non-interactive in libOSMesa8-32bit
sudo zypper --non-interactive in libp11-kit0-32bit
sudo zypper --non-interactive in libpartio1
sudo zypper --non-interactive in libpcap1-32bit
sudo zypper --non-interactive in libpcre2-8-0-32bit
sudo zypper --non-interactive in libpipewire-0_3-0-32bit
sudo zypper --non-interactive in libplank1
sudo zypper --non-interactive in libpng12-0-32bit
sudo zypper --non-interactive in libpolkit-qt5-1-1
sudo zypper --non-interactive in libportaudio2-32bit
sudo zypper --non-interactive in libpostproc55_9
sudo zypper --non-interactive in libpsl5-32bit
sudo zypper --non-interactive in libpulse0-32bit
sudo zypper --non-interactive in libpystring0_0
sudo zypper --non-interactive in libQt5Bluetooth5
sudo zypper --non-interactive in libQt5Concurrent5
sudo zypper --non-interactive in libQt5Help5
sudo zypper --non-interactive in libQt5NetworkAuth5
sudo zypper --non-interactive in libQt5Nfc5-imports
sudo zypper --non-interactive in libQt5Pas1
sudo zypper --non-interactive in libqt5-qtconnectivity-tools
sudo zypper --non-interactive in libQt5SerialPort5
sudo zypper --non-interactive in libQt5WebSockets5
sudo zypper --non-interactive in libQt5WebSockets5-imports
sudo zypper --non-interactive in libQt5Xml5
sudo zypper --non-interactive in libQt6Gui6
sudo zypper --non-interactive in libQt6Widgets6
sudo zypper --non-interactive in librav1e0-32bit
sudo zypper --non-interactive in librnnoise0
sudo zypper --non-interactive in librtmp1
sudo zypper --non-interactive in libsbc1-32bit
sudo zypper --non-interactive in libSDL2-2_0-0-32bit
sudo zypper --non-interactive in libSDL2_net-2_0-0
sudo zypper --non-interactive in libserd-0-0-32bit
sudo zypper --non-interactive in libsha1detectcoll1
sudo zypper --non-interactive in libsignon-qt5-1
sudo zypper --non-interactive in libslopy7_6
sudo zypper --non-interactive in libSM6-32bit
sudo zypper --non-interactive in libsndio7_1
sudo zypper --non-interactive in libsord-0-0-32bit
sudo zypper --non-interactive in libspdlog1_11
sudo zypper --non-interactive in libspeexdsp1
sudo zypper --non-interactive in libsqlite3-0-32bit
sudo zypper --non-interactive in libssh4-32bit
sudo zypper --non-interactive in libstdc++6-devel-gcc13
sudo zypper --non-interactive in libstdc++6-pp-32bit
sudo zypper --non-interactive in libstdc++-devel-32bit
sudo zypper --non-interactive in libswresample3_9
sudo zypper --non-interactive in libswresample4_ff5
sudo zypper --non-interactive in libswscale6
sudo zypper --non-interactive in libtalloc2-32bit
sudo zypper --non-interactive in libtdb1-32bit
sudo zypper --non-interactive in libthai0-32bit
sudo zypper --non-interactive in libtiff6-32bit
sudo zypper --non-interactive in libtool-32bit
sudo zypper --non-interactive in libtspi1
sudo zypper --non-interactive in libudev1-32bit
sudo zypper --non-interactive in libunwind8-32bit
sudo zypper --non-interactive in libusbmuxd-2_0-6
sudo zypper --non-interactive in libutf8proc2
sudo zypper --non-interactive in libuuid-devel
sudo zypper --non-interactive in libv4lconvert0-32bit
sudo zypper --non-interactive in libva-glx2-32bit
sudo zypper --non-interactive in libvamp-sdk2
sudo zypper --non-interactive in libvdpau1-32bit
sudo zypper --non-interactive in libvorbis0-32bit
sudo zypper --non-interactive in libvorbisfile3-32bit
sudo zypper --non-interactive in libvulkan_intel
sudo zypper --non-interactive in libvulkan_radeon
sudo zypper --non-interactive in libwayland-client0-32bit
sudo zypper --non-interactive in libwebp7-32bit
sudo zypper --non-interactive in libwx_baseu-suse9_0_0
sudo zypper --non-interactive in libwx_gtk2u_core-suse9_0_0
sudo zypper --non-interactive in libwx_gtk3u_core-suse9_0_0
sudo zypper --non-interactive in libX11-xcb1-32bit
sudo zypper --non-interactive in libXau6-32bit
sudo zypper --non-interactive in libxcb-damage0
sudo zypper --non-interactive in libxcb-dri3-0-32bit
sudo zypper --non-interactive in libxcb-randr0-32bit
sudo zypper --non-interactive in libxcb-screensaver0
sudo zypper --non-interactive in libxcb-sync1-32bit
sudo zypper --non-interactive in libxcrypt-devel
sudo zypper --non-interactive in libXdamage1-32bit
sudo zypper --non-interactive in libXext6-32bit
sudo zypper --non-interactive in libXfixes3-32bit
sudo zypper --non-interactive in libXft2-32bit
sudo zypper --non-interactive in libXi6-32bit
sudo zypper --non-interactive in libXinerama1-32bit
sudo zypper --non-interactive in libxml2-2-32bit
sudo zypper --non-interactive in libXpm4-32bit
sudo zypper --non-interactive in libXrandr2-32bit
sudo zypper --non-interactive in libXrender1-32bit
sudo zypper --non-interactive in libxshmfence1-32bit
sudo zypper --non-interactive in libxslt-tools
sudo zypper --non-interactive in libXtst6-32bit
sudo zypper --non-interactive in libxvidcore4
sudo zypper --non-interactive in libXxf86vm1-32bit
sudo zypper --non-interactive in libyaml-0-2-32bit
sudo zypper --non-interactive in libyuv0-32bit
sudo zypper --non-interactive in libz1-32bit
sudo zypper --non-interactive in libzen0
sudo zypper --non-interactive in libzip5
sudo zypper --non-interactive in libzstd1-32bit
sudo zypper --non-interactive in libzstd-devel
sudo zypper --non-interactive in linux-glibc-devel
sudo zypper --non-interactive in lmms
sudo zypper --non-interactive in lsb-release
sudo zypper --non-interactive in lutris
sudo zypper --non-interactive in lv2
sudo zypper --non-interactive in lv2-calf
sudo zypper --non-interactive in lv2-rnnoise
sudo zypper --non-interactive in m4
sudo zypper --non-interactive in maim
sudo zypper --non-interactive in make
sudo zypper --non-interactive in makeinfo
sudo zypper --non-interactive in makeinfo-lang
sudo zypper --non-interactive in mangoapp
sudo zypper --non-interactive in mangohud
sudo zypper --non-interactive in mda-lv2
sudo zypper --non-interactive in mediainfo
sudo zypper --non-interactive in media-player-info
sudo zypper --non-interactive in meld
sudo zypper --non-interactive in meld-lang
sudo zypper --non-interactive in melt
sudo zypper --non-interactive in Mesa-32bit
sudo zypper --non-interactive in Mesa-demo
sudo zypper --non-interactive in Mesa-demo-egl
sudo zypper --non-interactive in Mesa-demo-es
sudo zypper --non-interactive in Mesa-dri-32bit
sudo zypper --non-interactive in Mesa-gallium-32bit
sudo zypper --non-interactive in Mesa-libGL1-32bit
sudo zypper --non-interactive in Mesa-libglapi0-32bit
sudo zypper --non-interactive in Mesa-vulkan-device-select
sudo zypper --non-interactive in Mesa-vulkan-device-select-32bit
sudo zypper --non-interactive in mingw64-libz
sudo zypper --non-interactive in mokutil
sudo zypper --non-interactive in movit8-data
sudo zypper --non-interactive in mozilla-nspr-32bit
sudo zypper --non-interactive in mozilla-nss-32bit
sudo zypper --non-interactive in mozilla-nss-certs-32bit
sudo zypper --non-interactive in mtools
sudo zypper --non-interactive in ncurses-devel
sudo zypper --non-interactive in ncurses-devel-32bit
sudo zypper --non-interactive in neofetch
sudo zypper --non-interactive in net-tools
sudo zypper --non-interactive in nilfs-utils
sudo zypper --non-interactive in nss-mdns-32bit
sudo zypper --non-interactive in obs-studio
sudo zypper --non-interactive in obs-studio-devel
sudo zypper --non-interactive in openldap2-devel
sudo zypper --non-interactive in openldap2-devel-32bit
sudo zypper --non-interactive in openshot-qt
sudo zypper --non-interactive in p11-kit-32bit
sudo zypper --non-interactive in pam-32bit
sudo zypper --non-interactive in pam-devel
sudo zypper --non-interactive in pam-devel-32bit
sudo zypper --non-interactive in pam_pwquality-32bit
sudo zypper --non-interactive in patch
sudo zypper --non-interactive in patterns-devel-base-devel_basis
sudo zypper --non-interactive in patterns-devel-base-devel_basis-32bit
sudo zypper --non-interactive in perl-Archive-Zip
sudo zypper --non-interactive in perl-Authen-SASL
sudo zypper --non-interactive in perl-Digest-HMAC
sudo zypper --non-interactive in perl-Error
sudo zypper --non-interactive in perl-File-RandomAccess
sudo zypper --non-interactive in perl-Git
sudo zypper --non-interactive in perl-Image-ExifTool
sudo zypper --non-interactive in perl-MailTools
sudo zypper --non-interactive in perl-Net-SMTP-SSL
sudo zypper --non-interactive in perl-Text-Unidecode
sudo zypper --non-interactive in pipewire-alsa-32bit
sudo zypper --non-interactive in pipewire-modules-0_3-32bit
sudo zypper --non-interactive in pipewire-spa-plugins-0_2-32bit
sudo zypper --non-interactive in plank
sudo zypper --non-interactive in plank-docklets
sudo zypper --non-interactive in plank-lang
sudo zypper --non-interactive in pluto
sudo zypper --non-interactive in pluto-bash-completion
sudo zypper --non-interactive in pluto-zsh-completion
sudo zypper --non-interactive in powerline-go
sudo zypper --non-interactive in prison-qt5-imports
sudo zypper --non-interactive in ptools
sudo zypper --non-interactive in pulseaudio-utils-32bit
sudo zypper --non-interactive in purpose
sudo zypper --non-interactive in pv
sudo zypper --non-interactive in python310-anyio
sudo zypper --non-interactive in python310-attrs
sudo zypper --non-interactive in python310-Automat
sudo zypper --non-interactive in python310-Babel
sudo zypper --non-interactive in python310-click
sudo zypper --non-interactive in python310-constantly
sudo zypper --non-interactive in python310-cssselect
sudo zypper --non-interactive in python310-distro
sudo zypper --non-interactive in python310-dnspython
sudo zypper --non-interactive in python310-evdev
sudo zypper --non-interactive in python310-Genshi
sudo zypper --non-interactive in python310-gevent
sudo zypper --non-interactive in python310-greenlet
sudo zypper --non-interactive in python310-gssapi
sudo zypper --non-interactive in python310-h11
sudo zypper --non-interactive in python310-h2
sudo zypper --non-interactive in python310-hpack
sudo zypper --non-interactive in python310-html5lib
sudo zypper --non-interactive in python310-httpcore
sudo zypper --non-interactive in python310-httpx
sudo zypper --non-interactive in python310-hyperframe
sudo zypper --non-interactive in python310-hyperlink
sudo zypper --non-interactive in python310-incremental
sudo zypper --non-interactive in python310-isodate
sudo zypper --non-interactive in python310-lxml
sudo zypper --non-interactive in python310-markdown-it-py
sudo zypper --non-interactive in python310-mdurl
sudo zypper --non-interactive in python310-numpy
sudo zypper --non-interactive in python310-olefile
sudo zypper --non-interactive in python310-Pillow
sudo zypper --non-interactive in python310-pyasn1
sudo zypper --non-interactive in python310-pyasn1-modules
sudo zypper --non-interactive in python310-pycares
sudo zypper --non-interactive in python310-Pygments
sudo zypper --non-interactive in python310-pyliblo
sudo zypper --non-interactive in python310-pyparsing
sudo zypper --non-interactive in python310-pytz
sudo zypper --non-interactive in python310-pyxdg
sudo zypper --non-interactive in python310-PyYAML
sudo zypper --non-interactive in python310-pyzmq
sudo zypper --non-interactive in python310-qt5
sudo zypper --non-interactive in python310-qt5-sip
sudo zypper --non-interactive in python310-qtwebengine-qt5
sudo zypper --non-interactive in python310-rdflib
sudo zypper --non-interactive in python310-requests-gssapi
sudo zypper --non-interactive in python310-requests-toolbelt
sudo zypper --non-interactive in python310-rich
sudo zypper --non-interactive in python310-scour
sudo zypper --non-interactive in python310-service_identity
sudo zypper --non-interactive in python310-simplejson
sudo zypper --non-interactive in python310-sniffio
sudo zypper --non-interactive in python310-tornado6
sudo zypper --non-interactive in python310-Twisted
sudo zypper --non-interactive in python310-Twisted-tls
sudo zypper --non-interactive in python310-typing_extensions
sudo zypper --non-interactive in python310-webencodings
sudo zypper --non-interactive in python310-zope.event
sudo zypper --non-interactive in python310-zope.interface
sudo zypper --non-interactive in python3-cepces
sudo zypper --non-interactive in python3-openshot
sudo zypper --non-interactive in python3-speechd
sudo zypper --non-interactive in q4wine
sudo zypper --non-interactive in q4wine-lang
sudo zypper --non-interactive in qpwgraph
sudo zypper --non-interactive in qsynth
sudo zypper --non-interactive in qsynth-lang
sudo zypper --non-interactive in qt6-imageformats
sudo zypper --non-interactive in qt6-network-tls
sudo zypper --non-interactive in qt6-platformtheme-gtk3
sudo zypper --non-interactive in qt6-translations
sudo zypper --non-interactive in qtractor
sudo zypper --non-interactive in replay-sorcery
sudo zypper --non-interactive in ripgrep
sudo zypper --non-interactive in ripgrep-bash-completion
sudo zypper --non-interactive in ripgrep-zsh-completion
sudo zypper --non-interactive in rnnoise-devel
sudo zypper --non-interactive in rubberband-cli
sudo zypper --non-interactive in samba-ad-dc-libs-32bit
sudo zypper --non-interactive in samba-client-32bit
sudo zypper --non-interactive in samba-client-libs-32bit
sudo zypper --non-interactive in samba-gpupdate
sudo zypper --non-interactive in samba-ldb-ldap
sudo zypper --non-interactive in samba-libs-32bit
sudo zypper --non-interactive in samba-winbind
sudo zypper --non-interactive in samba-winbind-libs
sudo zypper --non-interactive in samba-winbind-libs-32bit
sudo zypper --non-interactive in scummvm
sudo zypper --non-interactive in scummvm-extra
sudo zypper --non-interactive in scummvm-tools
sudo zypper --non-interactive in sgml-skel
sudo zypper --non-interactive in shotwell-lang
sudo zypper --non-interactive in signond
sudo zypper --non-interactive in signond-libs
sudo zypper --non-interactive in signon-kwallet-extension
sudo zypper --non-interactive in signon-plugin-oauth2
sudo zypper --non-interactive in signon-plugins
sudo zypper --non-interactive in signon-ui
sudo zypper --non-interactive in site-config
sudo zypper --non-interactive in solid-imports
sudo zypper --non-interactive in solid-tools
sudo zypper --non-interactive in sonnet
sudo zypper --non-interactive in sparse
sudo zypper --non-interactive in speech-dispatcher
sudo zypper --non-interactive in sqlite3
sudo zypper --non-interactive in sscep
sudo zypper --non-interactive in steam
sudo zypper --non-interactive in steam-devices
sudo zypper --non-interactive in steamtricks
sudo zypper --non-interactive in steamtricks-data
sudo zypper --non-interactive in subversion
sudo zypper --non-interactive in subversion-bash-completion
sudo zypper --non-interactive in subversion-perl
sudo zypper --non-interactive in suil-plugin-gtk2-in-qt5
sudo zypper --non-interactive in suil-plugin-qt5-in-gtk2
sudo zypper --non-interactive in suil-plugin-qt5-in-gtk3
sudo zypper --non-interactive in suil-plugin-x11-in-gtk2
sudo zypper --non-interactive in suil-plugin-x11-in-gtk3
sudo zypper --non-interactive in suil-plugin-x11-in-qt5
sudo zypper --non-interactive in syntax-highlighting
sudo zypper --non-interactive in syntax-highlighting-imports
sudo zypper --non-interactive in systemd-32bit
sudo zypper --non-interactive in system-user-games
sudo zypper --non-interactive in system-user-tss
sudo zypper --non-interactive in tack
sudo zypper --non-interactive in timidity
sudo zypper --non-interactive in traceroute
sudo zypper --non-interactive in trousers
sudo zypper --non-interactive in typelib-1_0-GnomeDesktop-3_0
sudo zypper --non-interactive in typelib-1_0-GtkSource-4
sudo zypper --non-interactive in typelib-1_0-JavaScriptCore-4_0
sudo zypper --non-interactive in typelib-1_0-JavaScriptCore-4_1
sudo zypper --non-interactive in typelib-1_0-Soup-2_4
sudo zypper --non-interactive in typelib-1_0-Soup-3_0
sudo zypper --non-interactive in typelib-1_0-WebKit2-4_0
sudo zypper --non-interactive in typelib-1_0-WebKit2-4_1
sudo zypper --non-interactive in udftools
sudo zypper --non-interactive in update-desktop-files
sudo zypper --non-interactive in usbmuxd
sudo zypper --non-interactive in vkbasalt
sudo zypper --non-interactive in vulkan-tools
sudo zypper --non-interactive in w3m
sudo zypper --non-interactive in w3m-inline-image
sudo zypper --non-interactive in webkit2gtk-4_0-injected-bundles
sudo zypper --non-interactive in wine-gecko
sudo zypper --non-interactive in wine-mono
sudo zypper --non-interactive in wine-staging
sudo zypper --non-interactive in wine-staging-32bit
sudo zypper --non-interactive in winetricks
sudo zypper --non-interactive in wxWidgets-lang
sudo zypper --non-interactive in xdotool
sudo zypper --non-interactive in xdotool-devel
sudo zypper --non-interactive in xmlcharent
sudo zypper --non-interactive in xorgproto-devel
sudo zypper --non-interactive in xwininfo
sudo zypper --non-interactive in yad
sudo zypper --non-interactive in yadm
sudo zypper --non-interactive in yadm-bash-completion
sudo zypper --non-interactive in yadm-zsh-completion
sudo zypper --non-interactive in yast2-theme-breeze
sudo zypper --non-interactive in zlib-devel
sudo zypper --non-interactive in zlib-devel-32bit
sudo zypper --non-interactive in zsh

sudo zypper ref && sudo zypper up
